### ISSUE TITLE
UIApplication.shared.canOpenURL should be used from main thread

### ISSUE THREAD

**Issue by leye0** [RaphaelWoude/capacitor-native-settings#10]
I received this warning...

> UI API called from background thread: UIApplication.canOpenURL(_:) must be used from main thread only

...when navigating back to my application.

It seems like the main thread should be retrieved before calling the `UIApplication.shared.canOpenURL` method. Maybe something like this would help?

```swift
DispatchQueue.main.async {
    UIApplication.shared.open(settingsUrl, completionHandler: { (success) in
        call.resolve([
            "status": success
        ])
    });
}
```

![image](https://user-images.githubusercontent.com/3464994/136231582-0f592198-5177-4138-befc-ef0cb3da6a5f.png)

Thanks

**Comment by RaphaelWoude** [comment]
That should do the trick. Would you be able to make a pull request for this?
