### ISSUE TITLE
Compatability with Capacitor v4?

### ISSUE THREAD

**Issue by philkonick** [RaphaelWoude/capacitor-native-settings#21]
Capacitor v4 has just been released, and I'm testing out compatibility with my app.

When running npm install with the v4.0.1 plugins present, this plugin throws a peer dependency error. However everything appears to work fine in app.

Can we get an update to avoid needing to run npm install with the --force tag? Much appreciated.

**Comment by benmarsh** [comment]
Having the same issue - would be great to get the dependency resolved. Thanks

**Comment by RaphaelWoude** [comment]
The plugin will be updated later this week when I have the time for it.

**Comment by MateiNenciu** [comment]
> The plugin will be updated later this week when I have the time for it.

I've made a PR: https://github.com/RaphaelWoude/capacitor-native-settings/pull/22

**Comment by RaphaelWoude** [comment]
Looking at the PR now. Been very busy with work last couple days.

**Comment by philkonick** [comment]
#22

**Comment by RaphaelWoude** [comment]
Merged. New version is now out on NPM.
