### ISSUE TITLE
error: package android.provider does not exist import static android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS;

### ISSUE THREAD

**Issue by naqeeb-klabs** [RaphaelWoude/capacitor-native-settings#25]
<img width="1552" alt="Screenshot 2022-09-27 at 7 36 31 PM" src="https://user-images.githubusercontent.com/52487587/192556416-525121f2-d803-450a-8b51-76a52ec6181e.png">

Getting this error while i am building android app. It is working fine for IOs.
my app is on Capacitor 3.

**Comment by RaphaelWoude** [comment]
Hello. Can you try rerunning Gradle and see if that fixes it?

**Comment by naqeeb-klabs** [comment]
i tried all the things but nothing worked then i updated the Capacitor from 3 to 4 then re add platform, then it worked.

**Comment by RaphaelWoude** [comment]
I have decided to update the README for more information about which versions go with what capacitor version.
**Capacitor 4**: Use **v4.0.0** or higher.
**Capacitor 3**: Use **v0.2.1** or lower.
