### ISSUE TITLE
Android/iOS Settings are not imported

### ISSUE THREAD

**Issue by aleksandar-brkic** [RaphaelWoude/capacitor-native-settings#29]
Both AndroidSettings and IOSSettings need to be imported in order for the example in the docs to work. If they are not, the error is that they are not defined.
![image](https://user-images.githubusercontent.com/116163972/196666461-7b2827d8-e8bd-4cac-b0cb-7c63abe95bba.png)

So this is what worked for me:
```
import {NativeSettings, AndroidSettings, IOSSettings} from 'capacitor-native-settings'

export default {
  methods: {
    onInput(value) {
      NativeSettings.open({
        optionAndroid: AndroidSettings.AppNotification,
        optionIOS:     IOSSettings.App,
      })
      ...
```

**Comment by RaphaelWoude** [comment]
Will update the README tonight.
