### ISSUE TITLE
Add CI (GitHub Actions)

### ISSUE THREAD

**Issue by dennisameling** [RaphaelWoude/capacitor-native-settings#3]
- For running checks on every PR/commit, you can check https://github.com/capacitor-community/bluetooth-le/blob/main/.github/workflows/main.yml
- For automatically publishing to NPM on a Git tag push, see https://github.com/dennisameling/muuri-angular/blob/master/.github/workflows/npm-publish.yml

**Comment by RaphaelWoude** [comment]
- [ ] PR/Commit
- [ ] Publish
