### ISSUE TITLE
Release a Capacitor 5 version

### ISSUE THREAD

**Issue by ptmkenny** [RaphaelWoude/capacitor-native-settings#30]
Capacitor 5 is now in beta and has minimal changes for plugins.  There's a [plugin update guide](https://capacitorjs.com/docs/next/updating/plugins/5-0).

It would be great to have a capacitor 5-compatible version of this plugin.

**Comment by typefox09** [comment]
Yes please, this would be great

**Comment by RaphaelWoude** [comment]
Live in v5.0.0
