### ISSUE TITLE
Location permission setting direct open in IOS device setting

### ISSUE THREAD

**Issue by dhruvi7489** [RaphaelWoude/capacitor-native-settings#39]
Hi guys,

App store rejecting my apk because of security reasons to given access in my app.

My code:
 NativeSettings.open({
                                optionAndroid: AndroidSettings.ApplicationDetails,
                                optionIOS: IOSSettings.App
                            }).then((res: any) => {
                                // Code
                            }).catch((err: any) => {
                                // Code
                            })

But in this module i don't find any specific way to open device setting directly to location access permission.

Can anyone suggest me how i can give specific location access permission in IOS?

**Comment by RaphaelWoude** [comment]
Hi @dhruvi7489 

Apple is very vague with what they allow for applications these days. The package supports different options outside of IOSSettings.App but we don't know if these are allowed at this moment in time as Apple does not provide us with a list of allowed and disallowed options.

You can try IOSSettings.Location but I cannot guarantee that this will not be rejected.
