### ISSUE TITLE
Problem when trying to run.

### ISSUE THREAD

**Issue by LeonardoRochaInacio** [RaphaelWoude/capacitor-native-settings#41]
It was tested in gradle 8.0.0 with capacitor-native-settings 5.0.0 and 5.0.1. The following error is displayed:

[capacitor] × Running Gradle build - failed!
[capacitor] [error] 
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]
[capacitor]         * Where:
[capacitor]         Settings file 'C:\......\android\settings.gradle' line: 5
[capacitor]
[capacitor]         * What went wrong:
[capacitor]         A problem occurred evaluating settings 'android'.
[capacitor]         > Could not open dsl generic class cache for script 'C:\....\android\capacitor.settings.gradle' (C:\Users\....\.gradle\caches\8.0.2\scripts\17bc3sygz4ahd3d0s8rt4pb12).
[capacitor]         > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64
[capacitor]
[capacitor]         * Try:
[capacitor]         > Run with --stacktrace option to get the stack trace.
[capacitor]         > Run with --info or --debug option to get more log output.
[capacitor]         > Run with --scan to get full insights.
[capacitor]
[capacitor]         * Get more help at https://help.gradle.org
[capacitor]
[capacitor]         BUILD FAILED in 647ms
[capacitor]
[ERROR] An error occurred while running subprocess capacitor.

Some solution for that?

**Comment by RaphaelWoude** [comment]
Hi @LeonardoRochaInacio,

What version of the JDK are you using?

**Comment by LeonardoRochaInacio** [comment]
Sorry about my late response. It was totally random. I've tried in another day, building it again and it worked.
