### ISSUE TITLE
Add support for Capacitor 6

### ISSUE THREAD

**Issue by edosenseidotcom** [RaphaelWoude/capacitor-native-settings#44]
The [first release candidate of Capacitor 6](https://github.com/ionic-team/capacitor/releases/tag/6.0.0-rc.0) was released last month, and the official release is scheduled to occur soon.

It would be great to update this plugin to add Capacitor 6 support.

**Comment by B-UMA** [comment]
Yes, please.

**Comment by niconaso** [comment]
I created this [PR](https://github.com/RaphaelWoude/capacitor-native-settings/pull/46)

**Comment by RaphaelWoude** [comment]
Merged. Going to make some final changes before I sent the package to NPM.

**Comment by RaphaelWoude** [comment]
https://www.npmjs.com/package/capacitor-native-settings
