### ISSUE TITLE
Only one Open Method

### ISSUE THREAD

**Issue by EinfachHans** [RaphaelWoude/capacitor-native-settings#7]
Is there a reason you seperate the Methode in a **openIos** and **openAndroid**? I don't like that as i always have to add a platform detection before Plugin Call.

Why did you decide to do it like this and not like jn the Cordova one?

**Comment by RaphaelWoude** [comment]
I created the plugin like this because the naming of certain calls is not the same on every platform. For in the future I will create a generic method that will support this functionality.

**Comment by RaphaelWoude** [comment]
Draft has been up for a bit now. Android is done. Waiting on @dennisameling for iOS.

**Comment by reslear** [comment]
@dennisameling wait you for iOS :)

**Comment by dennisameling** [comment]
Just added the iOS code: https://github.com/RaphaelWoude/capacitor-native-settings/pull/19

Sorry for the delay!

**Comment by RaphaelWoude** [comment]
Merged. New version coming out this week.
